index:
    path: /
    controller: App\Controller\MainController::index

books:
  path: /books
  controller: App\Controller\BookController::list

book_add:
  path: /book_add
  controller: App\Controller\BookController::add
